### PR TITLE
Fixed output for secret_id and added resource id

### PR DESCRIPTION
**Pull request by vbontempi**
### Description

Fixed output for secret_id now returning the unique secret_id 
Added the resource id in the output

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Fixed output for secret_id now returning the unique secret_id
Added the resource id in the output

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by alex-reiff — APPROVED** [review]

**Review by shemau — APPROVED** [review]
I am not against this:

```icl
id = "us-east/1e43244c-fa2c-440a-a242-ce08925cca35/779d012a-e25b-55f8-18fc-6cf3b6024be3"
secret_crn = "crn:v1:bluemix:public:secrets-manager:us-east:a/abac0df06b644a9cabc6e44f55b3880e:1e43244c-fa2c-440a-a242-ce08925cca35:secret:779d012a-e25b-55f8-18fc-6cf3b6024be3"
secret_id = "779d012a-e25b-55f8-18fc-6cf3b6024be3"
```

id is not a documented output from the resource [sm_public_certificate](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/sm_public_certificate)

secret_id is a unique resource ID and included in both the others
id is enough to find the secret, region, service and secret id all of which is in the crn
crn contains additional information, the account id.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
